export type Lang = "en" | "es" | "sv";

const strings = {
  en: {
    // Check-in page
    checkinTitle: "Daily Check-In",
    checkinSubtitle: "How are you feeling today? Takes about 60 seconds.",
    dateLabel: "📅 Date",
    sleepHoursLabel: "🌙 Hours of sleep last night",
    sleepHoursPlaceholder: "e.g. 7.5",
    sleepQualityLabel: "Sleep quality",
    moodLabel: "Mood",
    anxietyLabel: "Anxiety level",
    focusLabel: "Focus & concentration",
    energyLabel: "Energy level",
    notesLabel: "📝 Notes",
    notesOptional: "(optional)",
    notesPlaceholder: "Anything else you'd like your clinician to know…",
    submitButton: "Submit check-in",
    submittingButton: "Submitting…",
    successTitle: "Check-in recorded!",
    successBody: "Your clinician can now see this entry. You can close this tab.",
    submitAnother: "Submit another",
    footerNote: "Your data is shared only with your clinician via EEGBase.",
    // Scale endpoints
    poorExcellent: ["Poor", "Excellent"] as [string, string],
    veryLowHigh: ["Very low", "Very high"] as [string, string],
    noneServerely: ["None", "Severe"] as [string, string],
    scatteredSharp: ["Scattered", "Sharp"] as [string, string],
    exhaustedEnergised: ["Exhausted", "Energised"] as [string, string],
    // Share page
    shareHeader: "Progress Report",
    shareSessions: "Sessions",
    shareAvgReward: "Avg. Reward Score",
    shareGoals: "Goals",
    shareFooter: "This report is generated by EEGBase and shared by your clinician.",
    shareDate: "Date",
    shareDuration: "Duration",
    shareDevice: "Device",
    shareReward: "Reward",
    // Lang toggle
    langEN: "EN",
    langES: "ES",
    langSV: "SV",
  },
  es: {
    // Check-in page
    checkinTitle: "Registro Diario",
    checkinSubtitle: "¿Cómo te sientes hoy? Tarda alrededor de 60 segundos.",
    dateLabel: "📅 Fecha",
    sleepHoursLabel: "🌙 Horas de sueño anoche",
    sleepHoursPlaceholder: "Ej. 7.5",
    sleepQualityLabel: "Calidad del sueño",
    moodLabel: "Estado de ánimo",
    anxietyLabel: "Nivel de ansiedad",
    focusLabel: "Concentración y enfoque",
    energyLabel: "Nivel de energía",
    notesLabel: "📝 Notas",
    notesOptional: "(opcional)",
    notesPlaceholder: "¿Algo más que quieras que sepa tu clínico?",
    submitButton: "Enviar registro",
    submittingButton: "Enviando…",
    successTitle: "¡Registro guardado!",
    successBody: "Tu clínico puede ver esta entrada ahora. Puedes cerrar esta pestaña.",
    submitAnother: "Enviar otro",
    footerNote: "Tus datos son compartidos solo con tu clínico a través de EEGBase.",
    // Scale endpoints
    poorExcellent: ["Mala", "Excelente"] as [string, string],
    veryLowHigh: ["Muy bajo", "Muy alto"] as [string, string],
    noneServerely: ["Ninguna", "Severa"] as [string, string],
    scatteredSharp: ["Dispersa", "Aguda"] as [string, string],
    exhaustedEnergised: ["Agotado/a", "Con energía"] as [string, string],
    // Share page
    shareHeader: "Informe de Progreso",
    shareSessions: "Sesiones",
    shareAvgReward: "Puntuación Media de Recompensa",
    shareGoals: "Objetivos",
    shareFooter: "Este informe es generado por EEGBase y compartido por tu clínico.",
    shareDate: "Fecha",
    shareDuration: "Duración",
    shareDevice: "Dispositivo",
    shareReward: "Recompensa",
    // Lang toggle
    langEN: "EN",
    langES: "ES",
    langSV: "SV",
  },
  sv: {
    // Check-in page
    checkinTitle: "Daglig Incheckning",
    checkinSubtitle: "Hur mår du idag? Det tar ungefär 60 sekunder.",
    dateLabel: "📅 Datum",
    sleepHoursLabel: "🌙 Sömntimmar förra natten",
    sleepHoursPlaceholder: "t.ex. 7.5",
    sleepQualityLabel: "Sömnkvalitet",
    moodLabel: "Humör",
    anxietyLabel: "Ångestnivå",
    focusLabel: "Fokus och koncentration",
    energyLabel: "Energinivå",
    notesLabel: "📝 Anteckningar",
    notesOptional: "(valfritt)",
    notesPlaceholder: "Finns det något annat du vill att din kliniker ska veta?",
    submitButton: "Skicka incheckning",
    submittingButton: "Skickar…",
    successTitle: "Incheckning registrerad!",
    successBody: "Din kliniker kan nu se denna post. Du kan stänga fliken.",
    submitAnother: "Skicka en till",
    footerNote: "Dina uppgifter delas bara med din kliniker via EEGBase.",
    // Scale endpoints
    poorExcellent: ["Dålig", "Utmärkt"] as [string, string],
    veryLowHigh: ["Mycket låg", "Mycket hög"] as [string, string],
    noneServerely: ["Ingen", "Svår"] as [string, string],
    scatteredSharp: ["Splittrad", "Skarp"] as [string, string],
    exhaustedEnergised: ["Utmattad", "Energisk"] as [string, string],
    // Share page
    shareHeader: "Framstegsrapport",
    shareSessions: "Sessioner",
    shareAvgReward: "Genomsnittlig belöningspoäng",
    shareGoals: "Mål",
    shareFooter: "Denna rapport genereras av EEGBase och delas av din kliniker.",
    shareDate: "Datum",
    shareDuration: "Varaktighet",
    shareDevice: "Enhet",
    shareReward: "Belöning",
    // Lang toggle
    langEN: "EN",
    langES: "ES",
    langSV: "SV",
  },
} as const;

export function t<K extends keyof typeof strings.en>(key: K, lang: Lang): typeof strings.en[K] {
  return strings[lang][key] as typeof strings.en[K];
}

export function detectLang(): Lang {
  if (typeof window === "undefined") return "en";
  const stored = localStorage.getItem("lang");
  if (stored === "en" || stored === "es" || stored === "sv") return stored;
  const nav = navigator.language.toLowerCase();
  if (nav.startsWith("sv")) return "sv";
  if (nav.startsWith("es")) return "es";
  return "en";
}
