export interface ProtocolTemplate {
  id: string;
  name: string;
  description: string;
  deviceType: "eeg" | "fnirs" | "both";
  targetBand: string;
  electrodes: string;
  sessionDurationMinutes: number;
  rewardThreshold: number;
  inhibitThreshold: number;
  category: string;
  evidence: string;
}

export const PROTOCOL_TEMPLATES: ProtocolTemplate[] = [
  {
    id: "smr-beta-adhd",
    name: "SMR/Beta ADHD",
    description: "Reward 12–15 Hz SMR and suppress 4–8 Hz theta. Gold-standard protocol for ADHD and attention difficulties.",
    deviceType: "eeg",
    targetBand: "SMR (12–15 Hz)",
    electrodes: "Cz, C3, C4",
    sessionDurationMinutes: 30,
    rewardThreshold: 65,
    inhibitThreshold: 35,
    category: "Attention",
    evidence: "Level 4 — Best Support (ISNR)",
  },
  {
    id: "alpha-theta-trauma",
    name: "Alpha/Theta Trauma",
    description: "Cross-over training between alpha (8–12 Hz) and theta (4–8 Hz) to facilitate trauma processing and relaxation.",
    deviceType: "eeg",
    targetBand: "Alpha (8–12 Hz) / Theta (4–8 Hz)",
    electrodes: "Pz",
    sessionDurationMinutes: 30,
    rewardThreshold: 70,
    inhibitThreshold: 30,
    category: "Trauma & PTSD",
    evidence: "Level 3 — Probably Efficacious",
  },
  {
    id: "frontal-alpha-depression",
    name: "Frontal Alpha Asymmetry",
    description: "Increase left frontal alpha relative to right to address depressive symptoms. Targets F3/F4 asymmetry.",
    deviceType: "eeg",
    targetBand: "Alpha Asymmetry (F3–F4)",
    electrodes: "F3, F4",
    sessionDurationMinutes: 25,
    rewardThreshold: 60,
    inhibitThreshold: 40,
    category: "Depression",
    evidence: "Level 2 — Possibly Efficacious",
  },
  {
    id: "beta-gamma-tbi",
    name: "Beta/Gamma TBI",
    description: "Upregulate 18–40 Hz beta/gamma to support cognitive recovery post-TBI. Inhibit excess theta.",
    deviceType: "eeg",
    targetBand: "Beta/Gamma (18–40 Hz)",
    electrodes: "Fz, Cz",
    sessionDurationMinutes: 20,
    rewardThreshold: 55,
    inhibitThreshold: 45,
    category: "TBI / Cognitive",
    evidence: "Level 2 — Possibly Efficacious",
  },
  {
    id: "delta-sleep",
    name: "Delta Suppression (Insomnia)",
    description: "Reduce daytime delta (1–4 Hz) which correlates with hypersomnolence; enhance SMR for sleep regulation.",
    deviceType: "eeg",
    targetBand: "Delta (1–4 Hz) suppression",
    electrodes: "Cz",
    sessionDurationMinutes: 30,
    rewardThreshold: 65,
    inhibitThreshold: 35,
    category: "Sleep",
    evidence: "Level 2 — Possibly Efficacious",
  },
  {
    id: "fnirs-frontal-attention",
    name: "fNIRS Frontal Attention",
    description: "Upregulate prefrontal OxyHb during cognitive tasks. Targets sustained attention and executive function.",
    deviceType: "fnirs",
    targetBand: "OxyHb (PFC)",
    electrodes: "Prefrontal bilateral",
    sessionDurationMinutes: 20,
    rewardThreshold: 60,
    inhibitThreshold: 40,
    category: "Attention",
    evidence: "Level 2 — Possibly Efficacious",
  },
  {
    id: "theta-burst-anxiety",
    name: "Theta Suppression (Anxiety)",
    description: "Inhibit excess frontal theta (4–8 Hz) associated with rumination and anxious arousal. Reward beta.",
    deviceType: "eeg",
    targetBand: "Theta (4–8 Hz) suppression",
    electrodes: "Fz, F3, F4",
    sessionDurationMinutes: 25,
    rewardThreshold: 60,
    inhibitThreshold: 40,
    category: "Anxiety",
    evidence: "Level 3 — Probably Efficacious",
  },
  {
    id: "peak-performance",
    name: "Peak Performance / Flow",
    description: "Optimise theta-alpha ratio at Fz for flow state induction. Used in sports and performance contexts.",
    deviceType: "eeg",
    targetBand: "Theta/Alpha ratio",
    electrodes: "Fz, Pz",
    sessionDurationMinutes: 20,
    rewardThreshold: 70,
    inhibitThreshold: 30,
    category: "Performance",
    evidence: "Level 2 — Possibly Efficacious",
  },
  {
    id: "ilf-othmer",
    name: "Infra-Low Frequency (Othmer)",
    description: "Bipolar training at sub-0.1 Hz frequencies tuned to the individual's Optimal Reinforcement Frequency. Broad-spectrum regulation tool.",
    deviceType: "eeg",
    targetBand: "ILF (< 0.1 Hz, individualised)",
    electrodes: "T4–P4 (right), T3–Fp1 (left)",
    sessionDurationMinutes: 30,
    rewardThreshold: 60,
    inhibitThreshold: 40,
    category: "Regulation",
    evidence: "Level 2 — Possibly Efficacious",
  },
  {
    id: "scp-epilepsy",
    name: "Slow Cortical Potentials (SCP)",
    description: "Bidirectional training of negative and positive SCPs at Cz. First-line non-pharmacological option for medication-resistant epilepsy.",
    deviceType: "eeg",
    targetBand: "Slow Cortical Potentials (DC)",
    electrodes: "Cz vs mastoid",
    sessionDurationMinutes: 30,
    rewardThreshold: 60,
    inhibitThreshold: 40,
    category: "Epilepsy",
    evidence: "Level 4 — Efficacious (ISNR)",
  },
  {
    id: "z-score-database",
    name: "Z-Score (4-channel database)",
    description: "Live z-score training against a normative database. Operant-conditions the metrics that are most deviated for the individual at any moment.",
    deviceType: "eeg",
    targetBand: "Live z-scored powers + coherence",
    electrodes: "Fz, Cz, Pz, Oz (or per qEEG)",
    sessionDurationMinutes: 30,
    rewardThreshold: 65,
    inhibitThreshold: 35,
    category: "qEEG-guided",
    evidence: "Level 3 — Probably Efficacious",
  },
  {
    id: "mu-rebalance-autism",
    name: "Mu Rhythm Rebalance",
    description: "Reward 8–13 Hz sensorimotor rhythm modulation at C3/C4. Targets mirror-neuron / social engagement dysregulation in autistic adults.",
    deviceType: "eeg",
    targetBand: "Mu (8–13 Hz)",
    electrodes: "C3, C4",
    sessionDurationMinutes: 25,
    rewardThreshold: 60,
    inhibitThreshold: 40,
    category: "Autism / Social",
    evidence: "Level 2 — Possibly Efficacious",
  },
  {
    id: "ocd-high-beta-inhibit",
    name: "High-Beta Inhibit (OCD)",
    description: "Inhibit 23–34 Hz high beta over right frontal regions associated with rumination loops. Reward 13–18 Hz beta.",
    deviceType: "eeg",
    targetBand: "High beta (23–34 Hz) inhibit",
    electrodes: "F4, Fp2",
    sessionDurationMinutes: 25,
    rewardThreshold: 60,
    inhibitThreshold: 40,
    category: "OCD",
    evidence: "Level 2 — Possibly Efficacious",
  },
  {
    id: "migraine-smr-c3c4",
    name: "Migraine SMR (Stokes)",
    description: "SMR/theta training at C3/C4 combined with relaxation. Reduces migraine frequency and severity by 50%+ in published series.",
    deviceType: "eeg",
    targetBand: "SMR (12–15 Hz) / theta inhibit",
    electrodes: "C3, C4 sequential",
    sessionDurationMinutes: 30,
    rewardThreshold: 65,
    inhibitThreshold: 35,
    category: "Migraine",
    evidence: "Level 4 — Efficacious (ISNR)",
  },
  {
    id: "hrv-coherence",
    name: "HRV Coherence (Resonance)",
    description: "Pace breathing at the individual's resonance frequency (typically 5.5–6 bpm) to maximise heart-rate variability and vagal tone.",
    deviceType: "both",
    targetBand: "HRV — RMSSD / RSA",
    electrodes: "Chest strap or forehead PPG",
    sessionDurationMinutes: 20,
    rewardThreshold: 60,
    inhibitThreshold: 40,
    category: "Autonomic / Stress",
    evidence: "Level 4 — Efficacious",
  },
  {
    id: "fnirs-pfc-lateralised",
    name: "fNIRS PFC Lateralised",
    description: "Train left-right asymmetry of prefrontal OxyHb. Useful for executive-function deficits where one hemisphere is hypoactive.",
    deviceType: "fnirs",
    targetBand: "OxyHb laterality index",
    electrodes: "Prefrontal bilateral (Mendi geometry)",
    sessionDurationMinutes: 25,
    rewardThreshold: 60,
    inhibitThreshold: 40,
    category: "Executive function",
    evidence: "Level 2 — Possibly Efficacious",
  },
  {
    id: "coherence-training",
    name: "Coherence Training",
    description: "Train or inhibit cross-site EEG coherence (typically reduce hyper-coherent pairs). Useful for connectivity-driven presentations.",
    deviceType: "eeg",
    targetBand: "Coherence — alpha, beta bands",
    electrodes: "Per qEEG pair (e.g. F3–F4)",
    sessionDurationMinutes: 25,
    rewardThreshold: 60,
    inhibitThreshold: 40,
    category: "qEEG-guided",
    evidence: "Level 2 — Possibly Efficacious",
  },
  {
    id: "alpha-uptraining-meditation",
    name: "Alpha Uptraining (Meditation)",
    description: "Reward 8–12 Hz posterior alpha with eyes closed. Cultivates the relaxed-aware state observed in long-term meditators.",
    deviceType: "eeg",
    targetBand: "Posterior alpha (8–12 Hz)",
    electrodes: "Pz, O1, O2",
    sessionDurationMinutes: 30,
    rewardThreshold: 65,
    inhibitThreshold: 35,
    category: "Meditation / Calm",
    evidence: "Level 3 — Probably Efficacious",
  },
  {
    id: "scp-migraine",
    name: "SCP Migraine Prophylaxis",
    description: "Bidirectional Slow Cortical Potential training at Cz. Documented prophylactic effect on migraine attack frequency in RCT.",
    deviceType: "eeg",
    targetBand: "Slow Cortical Potentials (DC)",
    electrodes: "Cz vs mastoid",
    sessionDurationMinutes: 30,
    rewardThreshold: 60,
    inhibitThreshold: 40,
    category: "Migraine",
    evidence: "Level 3 — Probably Efficacious",
  },
];
